FROM debian:jessie-slim
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y ca-certificates
RUN mkdir /app

ADD ./pilot /app/pilot
ADD ./index.html /app/index.html
ADD ./pilot.css /app/pilot.css

WORKDIR /
