FROM debian:jessie-slim
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y ca-certificates
RUN mkdir /app

ADD ./pilot /app/pilot

RUN mkdir /www
ADD ./index.html /www/index.html
ADD ./pilot.css /www/pilot.css

WORKDIR /
